# Generated by Django 6.0.2 on 2026-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rangi', models.CharField(max_length=10)),
                ('yoqilgi_turi', models.CharField(max_length=20)),
                ('turi', models.CharField(max_length=20)),
                ('diska_turi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
