# Generated by Django 6.0.2 on 2026-02-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('otasinging_ismi', models.CharField(max_length=100)),
                ('tugilgan_kun', models.DateField()),
                ('yashash_joyi', models.TextField()),
                ('telefon_raqami', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
